[toc]

### 异常处理总结

#### 捕获异常

try ：执行可能产生异常的代码

catch：捕获异常

finally：无论是否发生异常代码总被执行

#### 抛出异常

throw：==异常的生产阶段==：手动抛出异常对象

throws：==异常的处理方式：==声明方法可能要抛出的各种异常类

#### java异常处理的抓抛模型

 * 异常的处理：抓抛模型
 * 过程一：“抛”：程序在正常执行的过程中，一旦出现异常，就会在异常代码处生产一个对应异常类的对象
 * 并将此对象抛出。
 * 一旦抛出对象后，其后的代码就不在执行
 * 关于异常对象的产生：① 系统自动生成的异常对象
 * ② 手动的生成一个异常对象，并抛出(throw)，throw new 异常类型();
 * ③ 自定义异常类型
 * 过程二：“抓”：可以理解异常的处理方式：try-catch-finally 和 throws 

#### 异常处理方式一：try-catch-finally

##### try-catch-finally的使用

```java
  try{
  //可能出现异常的代码	
  }catch(异常类型1 变量名1){
  //处理异常类型1
  }catch(异常类型2 变量名2){
  //处理异常类型2
  }catch(异常类型3 变量3){
  //处理异常类型3
  }
 // ...
 finally{
  //一定会执行的代码
  }
```

 * 说明：
 * 1.finally是可选的
 * 2.使用try将可能出现异常的代码包起来，在执行过程中，一旦出现异常，就会生成一个对应异常类的对象，根据此对象的类
 * 型，去catch中进行匹配
 * 3.一旦try中的异常对象匹配到某个catch时，就进入catch中进行异常处理，一旦处理完成就跳出当前try-catch结构（在没有写finally的前提下）
 * 继续执行其后的代码
 * 4.catch中的异常类型在没有子父类时，前后顺序无所谓；在有子父类关系时，若父类写在前子类在后，就会报错.
 * 5.常用的异常处理的方式，① 使用getMessage()方法  ② 使用printStackTrace()方法   
 * 6.在try结构中声明的变量，在出了try结构就不能被调用了

##### 如何看待代码中的编译时异常和运行时异常？
* 体会1：使用try-catch-finally处理编译时异常，是得程序在编译时就不再报错，但是运行时仍可能报错。相当于我们使用try-catch-finally将一个编译时可能出现的异常，延迟到运行时出现。
* 体会2：开发中，由于运行时异常比较常见，所以我们通常就不针对运行时异常编写try-catch-finally了。针对于编译时异常，我们说一定要考虑异常的处理。

##### finally的再说明：
1. finally是可选的
2. finally中声明的是一定会被执行的代码。即使catch中又出现异常了，try中return语句，catch中return语句等情况。
3. 像数据库连接、输入输出流、网络编程Socket等资源，JVM是不能自动的回收的，我们需要自己手动的进行资源的释放。此时的资源释放，就需要声明在finally中。

##### final、finally、finalize三者的区别

throw和throws区别

Collection 和 Collections区别

ArrayList、StringBuffer、StringBuilder区别

HashMap、LinkedHashMap区别

重写 、重载区别

== 、equals()区别

sleep()、wait()区别

#### 异常处理方式二：throws

"throws+异常类型“写在方法的声明处。指明此方法执行时，可能会抛出的异常类型。
一旦当方法体执行时，出现异常，仍会在异常代码处生成一个异常类的对象，此对象满足throws后异常类型时，就会被抛出。异常代码后续的代码，就不再执行！

#### 对比两种方式

* try-catch-finally：真正的将异常给处理掉了。
* throws:的方式只是将异常抛给了方法的调用者。并没真正将异常处理掉。

#### 开发中如何运用

* 如果父类中被重写的方法没throws方式处理异常，则子类重写的方法也不能使用throws，意味着如果子类重写的方法中异常，必须使用try-catch-finally方式处理。

* 执行的方法a中，先后又调用了另外的几个方法，这几个方法是递进关系执行的。
  我们建议这几个方法使用throws的方式进行处理。而执行的方法a可以考虑使用try-catch-
  finally方式进行处理。

  ##### 补充

  方法重写的规则之一：
  仔类重写的方法抛出的异常类型不大于父类被重写的方法抛出的异常类型

#### 手动抛出异常

##### 使用说明

在程序执行中，除了自动抛出异常对象的情况之外，我们还可以手动的throw一个异常类的对象。

##### throw和throws区别

1. throw表示抛出一个异常类的对象，生成异常对象的过程。声明在方法体内。
2. throws属于异常处理的一种方式，声明在方法的声明处。

##### 例子

```java
/*
 * 手动抛出异常throw new 异常类型()
 * 
 * */
public class StudentTest {
	public static void main(String[] args) {
		
		try {
			Student s = new Student();
			s.regist(-1);
			System.out.println(s);
		} catch (MyException e) {
			// TODO Auto-generated catch block
//			e.printStackTrace();
			System.out.println(e.getMessage());
		}
		
	}
}

class Student{
	int id;
	
	public void regist(int id){
		if(id>0) {
			this.id = id;
		}else {
//			System.out.println("您输入的数据非法");
			//手动抛出异常对象throw 注意：没有“s”
			//throw new RuntimeException("您输入的数据非法");
//			throw new Exception("您输入的数据非法");
			throw new MyException("不能输入负数");
		}
		
	}
	
}
```

##### 自定义异常

```java
/*
 * 自定义异常类型
 * 	1.首先要去继承现有的异常结构：RuntimeException、Exception
 * 	2.提供全局常量：serialVersionUID 
 * 	3.提供重载构造器
 * 
 * */
public class MyException extends RuntimeException{
	static final long serialVersionUID = -7034897190745766939L;
	public MyException() {
		super();
	}
	
	public MyException(String msg) {
		super(msg);
	}
}

```

